ERROR: Unable to locate a modulefile for 'python/3.6.7'
[0;30;43mCpp extension not loaded[0m
>>SEED: 2020
[0;30;43mloading [../data/gowalla][0m
810128 interactions for training
217242 interactions for testing
gowalla Sparsity : 0.0008396216228570436
gowalla is ready to go
===========config================
{'A_n_fold': 100,
 'A_split': False,
 'bigdata': False,
 'bpr_batch_size': 2048,
 'decay': 0.0001,
 'dropout': 0,
 'keep_prob': 0.6,
 'latent_dim_rec': 64,
 'lightGCN_n_layers': 3,
 'lr': 0.001,
 'multicore': 0,
 'pretrain': 0,
 'test_u_batch_size': 100}
cores for test: 32
comment: lgn
tensorboard: 1
LOAD: 0
Weight path: ./checkpoints
Test Topks: [20]
using bpr loss
===========end===================
[0;30;43muse NORMAL distribution initilizer[0m
loading adjacency matrix
successfully loaded...
don't split the matrix
lgn is already to go(dropout:0)
load and save to /home/nns20006/5819/CSE-5819-Project/lightgcn/code/checkpoints/lgn-gowalla-3-64.pth.tar
[0;30;43m[TEST][0m
Traceback (most recent call last):
  File "main.py", line 45, in <module>
    Procedure.Test(dataset, Recmodel, epoch, w, world.config['multicore'])
  File "/home/nns20006/5819/CSE-5819-Project/lightgcn/code/Procedure.py", line 106, in Test
    rating = Recmodel.getUsersRating(batch_users_gpu)
  File "/home/nns20006/5819/CSE-5819-Project/lightgcn/code/model.py", line 175, in getUsersRating
    all_users, all_items = self.computer()
  File "/home/nns20006/5819/CSE-5819-Project/lightgcn/code/model.py", line 166, in computer
    all_emb = torch.sparse.mm(g_droped, all_emb)
  File "/home/nns20006/miniconda3/envs/lightgcn/lib/python3.6/site-packages/torch/sparse/__init__.py", line 68, in mm
    return torch._sparse_mm(mat1, mat2)
RuntimeError: CUDA error: kernel launch failure when calling `cusparseXcoo2csr(handle, coorowind, i_nnz, i_m, csrrowptr, CUSPARSE_INDEX_BASE_ZERO)`
